myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from community import views
from accounts import views as account_views
urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.home, name='home'),
    path('postcreate/', views.postcreate, name='postcreate'),
    path('detail/<int:post_id>', views.detail, name='detail'),
    #127.0.0.1:8000/detail/postid
    path('new_comment/<int:post_id>', views.new_comment, name='new_comment'),

    path('login/', account_views.login, name='login'),
    path('logout/', account_views.logout, name='logout'),
    path('signup/', account_views.signup, name='signup'),

    path('freehome/', views.freehome, name="freehome"),
    path('freepostcreate/', views.freepostcreate, name='freepostcreate'),
    path('freedetail/<int:post_id>', views.freedetail, name='freedetail'),
    path('new_freecomment/<int:post_id>', views.new_freecomment, name='new_freecomment'),

    path('accounts/', include('allauth.urls')),
]

myproject/accounts/models.py
from django.db import models

# Create your models here.

myproject/community/models.py
from tkinter import CASCADE
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# 게시물 모델(ORM)
class Post(models.Model):
    title = models.CharField(max_length=200) 
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.comment 

class FreePost(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author= models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.title 

class FreeComment(models.Model):
    comment = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(FreePost, null=True, blank=True, on_delete=models.CASCADE)
    author= models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.comment 

myproject/community/forms.py
from django import forms
from .models import Post, Comment, FreePost, FreeComment

class PostForm(forms.ModelForm):
    class Meta:
        model=Post 
        fields = '__all__'
        # fields = ['title', 'body']
    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs = {
            'class':'form-control',
            'placeholder':"글 제목을 입력해주세요",
            'rows':20
        }
        self.fields['body'].widget.attrs = {
            'class':'form-control',
            'placeholder':"글 본문을 입력해주세요",
            'rows':20,
            'cols':100
        }



class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment 
        fields = ['comment']
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)

        self.fields['comment'].widget.attrs = {
            'class':'form-control',
            'placeholder':"댓글을 입력해주세요",
            'rows':10
        }

class FreePostForm(forms.ModelForm):
    class Meta:
        model=FreePost 
        # fields = '__all__'
        fields = ['title', 'body']
    def __init__(self, *args, **kwargs):
        super(FreePostForm, self).__init__(*args, **kwargs)

        self.fields['title'].widget.attrs = {
            'class':'form-control',
            'placeholder':"글 제목을 입력해주세요",
            'rows':20
        }
        self.fields['body'].widget.attrs = {
            'class':'form-control',
            'placeholder':"글 본문을 입력해주세요",
            'rows':20,
            'cols':100
        }



class FreeCommentForm(forms.ModelForm):
    class Meta:
        model=FreeComment 
        fields = ['comment']
    def __init__(self, *args, **kwargs):
        super(FreeCommentForm, self).__init__(*args, **kwargs)

        self.fields['comment'].widget.attrs = {
            'class':'form-control',
            'placeholder':"댓글을 입력해주세요",
            'rows':10
        }

myproject/accounts/views.py
from django.shortcuts import redirect, render
from django.contrib import auth
from django.contrib.auth.models import User
# Create your views here.
def login(request):
    # request가 POST이면 로그인시키기
    if request.method == 'POST':
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('home')
        else:
            return render(request, 'bad_login.html')
    else: 
        return render(request, 'login.html')
        
def logout(request):
    auth.logout(request)
    return redirect('home')

def signup(request): 
    if request.method == "POST":
        if request.POST["password"] == request.POST["repeat"]:
            #회원가입
            new_user = User.objects.create_user(username=request.POST['username']
            ,password=request.POST['password'])
            # 로그인
            auth.login(request, new_user)
            # 홈 리다이렉션
            return redirect('home')
    return render(request, 'register.html')

myproject/community/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm, FreePostForm, FreeCommentForm
from .models import Post, FreePost
from django.core.paginator import Paginator
# Create your views here.
def home(request):
    # posts = Post.objects.all() 
    posts = Post.objects.filter().order_by('-date') #오름차순
    paginator = Paginator(posts, 5) #5개씩 끊어서
    pagenum = request.GET.get('page') #page가져오기
    posts= paginator.get_page(pagenum)
    return render(request, 'index.html', {'posts':posts})

def postcreate(request):
    #request method가 POST일 경우 입력값 저장
    if request.method == 'POST' or request.method== 'FILES':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save() 
            return redirect('home')
    #GET일 경우 form 입력 html 띄우기
    else:
        form = PostForm()
    return render(request, 'post_form.html', {'form':form})

def detail(request, post_id):
    post_detail = get_object_or_404(Post, pk=post_id)
    comment_form = CommentForm()
    return render(request, 'detail.html', {'post_detail':post_detail, 'comment_form':comment_form})

#댓글 저장
def new_comment(request, post_id): 
    filled_form = CommentForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False)
        finished_form.post= get_object_or_404(Post, pk=post_id) #외래키까지 저장하고 저장
        finished_form.save()
    return redirect('detail', post_id)

#----------------------------------------------------------------------------------------------
# 자유게시판
def freehome(request):
    # posts = Post.objects.all() 
    posts = FreePost.objects.filter().order_by('-date') #오름차순
    return render(request, 'free_index.html', {'posts':posts})

def freepostcreate(request):
    #request method가 POST일 경우 입력값 저장
    if request.method == 'POST' or request.method== 'FILES':
        form = FreePostForm(request.POST, request.FILES)
        if form.is_valid():
            unfinished = form.save(commit=False)
            unfinished.author = request.user
            unfinished.save() 
            return redirect('freehome')
    #GET일 경우 form 입력 html 띄우기
    else:
        form = FreePostForm()
    return render(request, 'free_post_form.html', {'form':form})

def freedetail(request, post_id):
    post_detail = get_object_or_404(FreePost, pk=post_id)
    comment_form = FreeCommentForm()
    return render(request, 'free_detail.html', {'post_detail':post_detail, 'comment_form':comment_form})

#댓글 저장
def new_freecomment(request, post_id): 
    filled_form = FreeCommentForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False)
        finished_form.post= get_object_or_404(FreePost, pk=post_id) #외래키까지 저장하고 저장
        finished_form.author = request.user
        finished_form.save()
    return redirect('freedetail', post_id)

myproject/accounts/templates/bad_login.html
<h1>존재하지않는 회원입니다. 다시 로그인해주세요</h1>
<br />
<a href="{% url 'login' %}">다시 로그인하기</a>

myproject/accounts/templates/login.html
{% load static %} {% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link
      href="{% static 'vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" />
  </head>

  <body class="bg-gradient-primary">
    <div class="container">
      <!-- Outer Row -->
      <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
          <div class="card o-hidden border-0 shadow-lg my-5">
            <div class="card-body p-0">
              <!-- Nested Row within Card Body -->
              <div class="row">
                <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                <div class="col-lg-6">
                  <div class="p-5">
                    <div class="text-center">
                      <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                    </div>
                    <form class="user" method="POST">
                      {% csrf_token %}
                      <div class="form-group">
                        <input
                          type="text"
                          class="form-control form-control-user"
                          id="username"
                          name="username"
                          aria-describedby="emailHelp"
                          placeholder="Enter your ID"
                        />
                      </div>
                      <div class="form-group">
                        <input
                          type="password"
                          class="form-control form-control-user"
                          id="password"
                          name="password"
                          placeholder="Password"
                        />
                      </div>
                      <input
                        type="submit"
                        value="login"
                        class="btn btn-primary btn-user btn-block"
                      />
                      <hr />
                      <a
                        href="{% provider_login_url 'google' %}"
                        class="btn btn-google btn-user btn-block"
                      >
                        <i class="fab fa-google fa-fw"></i> 구글 계정으로 로그인
                      </a>
                    </form>
                    <br />

                    <div class="text-center">
                      <a class="small" href="{% url 'signup' %}"
                        >Create an Account!</a
                      >
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  </body>
</html>

myproject/accounts/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>꿀팁 커뮤니티</title>

    <!-- Custom fonts for this template-->
    <link
      href="{% static 'vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" />
  </head>

  <body class="bg-gradient-primary">
    <div class="container">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <!-- Nested Row within Card Body -->
          <div class="row">
            <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
            <div class="col-lg-7">
              <div class="p-5">
                <div class="text-center">
                  <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
                </div>
                <form class="user" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                    <input
                      type="text"
                      class="form-control form-control-user"
                      id="exampleInputEmail"
                      name="username"
                      placeholder="Email your ID"
                    />
                  </div>
                  <div class="form-group row">
                    <div class="col-sm-6 mb-3 mb-sm-0">
                      <input
                        type="password"
                        class="form-control form-control-user"
                        id="exampleInputPassword"
                        name="password"
                        placeholder="Password"
                      />
                    </div>
                    <div class="col-sm-6">
                      <input
                        type="password"
                        class="form-control form-control-user"
                        id="exampleRepeatPassword"
                        name="repeat"
                        placeholder="Repeat Password"
                      />
                    </div>
                  </div>
                  <input
                    type="submit"
                    class="btn btn-primary btn-user btn-block"
                    value="회원가입"
                  />
                </form>
                <hr />
                <div class="text-center">
                  <a class="small" href="{% url 'login' %}"
                    >Already have an account? Login!</a
                  >
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  </body>
</html>

myproject/community/templates/forgot-password.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Forgot Password</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                        <p class="mb-4">We get it, stuff happens. Just enter your email address below
                                            and we'll send you a link to reset your password!</p>
                                    </div>
                                    <form class="user">
                                        <div class="form-group">
                                            <input type="email" class="form-control form-control-user"
                                                id="exampleInputEmail" aria-describedby="emailHelp"
                                                placeholder="Enter Email Address...">
                                        </div>
                                        <a href="login.html" class="btn btn-primary btn-user btn-block">
                                            Reset Password
                                        </a>
                                    </form>
                                    <hr>
                                    <div class="text-center">
                                        <a class="small" href="register.html">Create an Account!</a>
                                    </div>
                                    <div class="text-center">
                                        <a class="small" href="login.html">Already have an account? Login!</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

myproject/community/templates/form_create.html
<h1>django form을 이용한 새 글 작성 페이지</h1>
<!-- 한 url에서 get,post 다 처리 -->
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{form.as_table}}
  </table>
  <input type="submit" value="새 글 작성하기" />
</form>

myproject/community/templates/free_detail.html
{% extends 'base.html' %} {% block content %}
<h1>상세 페이지</h1>
<h2 class="alert alert-primary">제목 : {{ post_detail.title }}</h2>
<span class="badge rounded-pill bg-light">날짜 : {{ post_detail.date }}</span>
<br />
<span class="badge rounded-pill bg-light">본문 : {{ post_detail.body }}</span>
<br />
<span class="badge rounded-pill bg-light"
  >작성자 : {{ post_detail.author }}</span
>
<hr />

<!-- 댓글 목록 구간-->
{% for comment in post_detail.freecomment_set.all %} 작성 날짜:
<span class="badge rounded-pill bg-light"> {{comment.date }}</span>
<span class="badge rounded-pill bg-light"> {{comment }}</span> 작성자:
<span class="badge rounded-pill bg-light"> {{comment.author}}</span>
<hr />
{% endfor %}
<!-- 댓글 입력 구간-->
<form action="{% url 'new_freecomment' post_detail.id %}" method="POST">
  {% csrf_token %}
  <table>
    {{comment_form}}
  </table>
  <input
    type="submit"
    value="댓글 입력"
    class="btn btn-primary btn-icon-split"
  />
</form>
{% endblock %}

myproject/community/templates/index.html
{% extends 'base.html' %} {% block content %}
<!-- Begin Page Content -->
<div class="container-fluid">
  <!-- DataTales Example -->
  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">익명게시판</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table
          class="table table-bordered"
          id="dataTable"
          width="100%"
          cellspacing="0"
        >
          <thead>
            <tr>
              <th width="70%">글 제목</th>
              <th>작성 날짜</th>
              <th>작성자</th>
            </tr>
          </thead>
          <tbody>
            {% for post in posts %}
            <tr>
              <td><a href="{% url 'detail' post.id %}">{{post.title}}</a></td>
              <td>{{post.date}}</td>
              <td>익명</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<!-- /.container-fluid -->
{% if user.is_authenticated %}
<a href="{% url 'postcreate' %}" class="btn btn-primary btn-icon-split">
  <span class="icon text-white-50">
    <i class="fas fa-flag"></i>
  </span>
  <span class="text">글쓰기</span>
</a>
{% else %} {% endif %}
<!--페이지네이션-->
{% if posts.has_previous %}
<a href="?page=1">첫 페이지</a>
<a href="?page={{posts.previous_page_number}}">이전 페이지</a>
{% endif %}
<!-- 현재 페이지 -->
<span> {{posts.number}}</span>
<span> / </span>
<span> {{posts.paginator.num_pages }}</span>
<!-- 총 페이지 수 -->
{% if posts.has_next %}
<a href="?page={{posts.next_page_number}}">다음 페이지</a>
<a href="?page={{posts.paginator.num_pages}}">마지막 페이지</a>
{% endif %} {% endblock %}

myproject/community/templates/new.html
<form action="{% url 'create' %}" method="POST">
  {% csrf_token %}
  <!--보안-->
  <div>
    <label for="title">제목</label><br />
    <input type="text" name="title" id="title" />
  </div>
  <div>
    <label for="body">본문</label><br />
    <textarea name="body" id="body" cols="30" rows="10"></textarea>
  </div>
  <input type="submit" value="글 생성하기" />
</form>

myproject/community/templates/post_form.html
{% extends 'base.html' %} {% block content %}
<h1>새 글 작성</h1>
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{form.as_table}}
  </table>
  <input type="submit" value="새 글 " />
</form>
{% endblock %}